server:
  port: 9001
spring:
  application:
    name: tensquare_base
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.200.138:3306/tensquare_base
    username: root
    password: 123456
  jpa:
    database: MySQL
    show-sql: true
    generate-ddl: true


eureka:
  client:
    service-url:
      dafaultZone: http://localhost:6868/eureka
  instance:
    prefer-ip-address: true