server:
  port: 9009
spring:
  application:
    name: tensquare-sms
  rabbitmq:
    host: 192.168.200.138
aliyun:
  sms:
    accessKeyId: 不告诉你
    accessKeySecret: 不告诉你
    template_code: SMS_85735065
    sign_name: RookieWZW


eureka:
  client:
    service-url:
      dafaultZone: http://localhost:6868/eureka
  instance:
    prefer-ip-address: true