server:
  port: 9006
spring:
  application:
    name: tensquare-spit
  data:
    mongodb:
      host: 192.168.200.138
      database: spitdb
  redis:
    host: 192.168.200.138
  rabbitmq:
    host: 192.168.200.138


eureka:
  client:
    service-url:
      dafaultZone: http://localhost:6868/eureka
  instance:
    prefer-ip-address: true